# *- Mode:org; coding:utf-8-auto-unix; lexical-binding:t;-*-
# Time-stamp: <2023-08-31 18:11:10 vladimir>
# Time-stamp: <2023-08-13 12:39:07 vladimir>
# Copyright (C) 2019-2023 Vladimir G. Ivanović
# Author: Vladimir G. Ivanović <vladimir@acm.org>
#+title: Notes and To Dos

* What graphs/tables should I generate? And why.
- # of student, # of sites vs time
  This is a measure of their size and it also determines how much LCFF money they are going to receive.
- Revenues, expenditures vs time
  This measures their growth over time.
- Revenues, expenditures/student over time
  This measures how much they receive and spend per child over time.
- Cash flow vs time
  Cash is king.
- Debt vs time
  How much do they have to borrow to obtain the cash flow they want?
- Debt/student vs time
  Do they have economies of scale?
- Rocketship Support Network revenue vs time
  How much are their schools financing their growth?
* Zoom with Roxana, Wednesday, 16 August 2023
** To talk about
[] How was her keynote?
[] Mention tesseract and ocrmypdf. They are fantastic. They soak up a lot (A LOT) of CPU, but they have turned every PDF (image) I've asked them to into a real PDF (PDF/A, the archival PDF version). I even processed a 645 page petition (100% CPU for ~7 minutes).
[] Example of hiccups: Took Data Dashboard -> extracted a piece -> saved as PDF -> burst the PDF -> incorporated into dissertation -> used pdftk to join two pages into one -> used 'pdfpages' in LaTex to do what I wanted. Still to do, add headers and get rid of the blank page.

*  San Jose Insider
Judgment Day for Rocketship
By Joseph DiSalvo / December 13, 20117Z.L7VAo\&A7-!eb

There is a game-changing local story about to take place in a few days. A decision before the SCCOE Board of Education is whether or not to approve 20 Rocketship Charter Schools on a countywide benefit charter basis. Each new school approval is listed as a separate action item on the Board’s agenda. For each item, the county staff recommends approval insofar as the petition “meets the minimum requirements for countywide charter approval set forth in Educational Code section 47605.6.”

The turf wars are just beginning. President Pam Parker of the Santa Clara County School Board’s Association sent an email on Sunday to all SCC school board members entitled, “A Call To Arms.” President Parker wrote in her email, “… I feel it is imperative that we take a stand now or suffer the consequences in the future.” Parker was asking SCC school board members to attend the meeting and voice their concern about an affirmative vote by the County Board to approve.

The seeds of this remarkable Rocketship story were planted over decade ago in a parish church a block away from where my father grew up as first-generation Italian immigrant. In 1999, Father Mateo Sheedy, Pastor of Sacred Heart Church, was commissioned by Santa Clara University to find student candidates from the parish who could succeed at a four-year university. Father Sheedy quickly learned that the public schools in the area were failing to meet the educational needs of their students. He could not find one student qualified to have the requisite skills and courses to succeed at SCU.

Working to solve this problem, Father Sheedy dreamed big. He envisioned chartering local schools that would develop models of learning with high expectations for each student. The Pastor turned to John Danner, CEO of Rocketship who co-founded Sacred Heart Nativity School, a private Catholic school in 2000 for at-risk Latino boys (and now girls) in grades 6-8. Five years later he petitioned San Jose Unified School District for a charter K-5 grade school to address the issues of underserved, mostly Latino youth in downtown San Jose.

San Jose Unified’s Board, on a recommendation from then Superintendent Inglesias, denied the charter petition. Months later on appeal to the SCCOE Board of Education, Rocketship Mateo Sheedy was authorized. This local story takes off from here, now with a national spotlight. To demonstrate how things are changing in the pursuit of a public education system responsive to all its students, in November 2011 the San Jose Unified School District Board, on a recommendation from Superintendent Mathews, voted 5-0 to approve its first Rocketship Charter School.

In its first year of operation (2007), based on the Academic Performance Index (API), Rocketship Mateo Sheedy became the highest ranked low-income elementary school in the county and seventh in the state. The learning model at Mateo Sheedy has received national attention and proven to be scalable and replicable, as the nonprofit public benefit corporation works on continuous improvement to its critical systems.

The chemistry of success for Rocketship Education and its current five schools has everything to do with:

1. Teacher quality, attracting the best and the brightest teachers using the Teach For America talent from top-tier universities from around the U.S.
2. An extended school day;
3. High expectations for each child;
4. Teacher Teaming;
5. Deep community and parent involvement;
6. Individualization for each child;
7. Blended learning using 100 minutes of instruction in a computer lab;
8. High Quality Professional Development and Coaching models;
9. Exceptional school-level leadership;
10. Quality formative assessments that inform instruction. 

These critical learning systems and beliefs at Rocketship Education have been honed by two local titans of school reform: Co-founders John Danner and the Chief Petitioner for Rocketship 9-28, Preston Smith. Professionally, I have come to know Danner and Smith as two local educational leaders deeply committed to the educational needs of underserved children.

San Jose/Silicon Valley is incredibly fortunate to have them residing and working in our midst. No doubt they have been game-changers for public education and the educational needs of children living in low socio-economic areas of San Jose. I think their respective backgrounds are instructive.

John Danner is the son of retired Superior Court Judge Alden Danner and husband of Allison Marston Danner, 40, a federal prosecutor and former law school professor. John served as a teacher in Nashville public schools for three years. He was the founding director of KIPP Academy Nashville. John possesses a Bachelor’s degree and Master’s Degree in Electrical Engineering from Stanford and a Master’s degree in Education Policy from Vanderbilt. Before his pursuit of education interests, he founded and served as CEO of NetGravity, an Internet advertising software company. John took NetGravity public and sold it to Doubleclick in 1999.

Preston Smith is currently the Chief Academic Officer of Rocketship Education. He was the principal and founder of L.U.C.H.A. Elementary School in Alum Rock School District (ARSD) in 2004. In 2006, L.U.C.H.A. earned an API of 881 and was the fourth-ranked high-poverty elementary school in the state. Before 2004, Preston taught first grade for three years at Arbuckle Elementary in ARSD. Smith graduated Phi Beta Kappa from the University of North Carolina at Chapel Hill. 

Eight districts are destined for a Rocketship school if the county board votes to grant the petition in its entirety. The lion share of schools will be in San Jose Unified (6) Alum Rock (4), Franklin-McKinley (3), and Oak Grove School District (3). Single schools are slated for Santa Clara Unified, Campbell Elementary, Evergreen, and Mount Pleasant school districts.

There are detractors of the Rocketship model who use statistical data to bolster their arguments. Some call the Rocketship bandwagon corporate and cookie-cutter schooling. I am opposed to the privatization of public education, yet I believe Rocketship is a local success story, as I described above, with the right motivation for success.

How I vote on Wednesday night will be determined by three-things:

1. Do I believe what they have written in their 394-page petition?
2. Do I think the children left behind in traditional public schools will be ill served by Rocketship’s charters?
3. Will the approval of 20 schools and a potential district the size of 15,000 students decrease the level of collaboration necessary to eliminate the achievement gap? Will this be especially true in districts working cooperatively with Rocketship like San Jose Unified and Franklin-McKinley?

Here is what Rocketship writes on page 19 of its petition: ”Rocketship is committed to ensuring that its schools are widely available to underserved students who are victims of the achievement gap. Approval of RS18 and other Rocketship countywide charter schools would allow Rocketship to further partner with the SCCOE in the work to realize the goals of SJ/SV2020 to eradicate the achievement gap within these neighborhoods and communities.”

For me, this pending vote has caused much consternation. The SCCOE as an organization must support our local school districts and not be at odds with their missions. At the same time, the SCCOE Board’s focus must be about what is best for the children—all children, and especially those who have been underserved for decades. It is a very tough call for me to make. I have thought about this moment of decision for months and now the moment is here.

Joseph Di Salvo is a member of the Santa Clara County Office of Education’s Board of Trustees. He is a San Jose native. His columns reflect his personal opinion.
13 Comments

    Approval 5 years ahead? Dec 13, 2011 @ 1:50 am

    You seem to sidestep the fact that most of the 20 schools are not slated to open any time soon. Some will not open for over 5 years. It seems counterproductive to approve any school that far in advance; it will not help any kid for 5 years, it might deter other charter operators to open a school nearby, it might even impede potential improvements in the targeted schools (what’s the point of improvement if the school is to be replaced by a charter in 5 years no matter what).
    If RocketShip wants to grow by 4 schools every year, why don’t you follow that progression and approve 4 more schools every year. It will give you much flexibility to allow for other charter operators, assess schools progress and see if a startup like RocketShip can really scale and live up to its early fame.

    Sure, it would make for a less impactful press release but those have nothing to with the kids.
    Reply
    Craig Mann Dec 13, 2011 @ 3:04 am

    Great column Joseph!  Much has been said about this topic.  Julia Hover-Smoot and I co-authored an article in the SJMN this past Sunday, December 11th which can be found on their site, http://www.mercurynews.com

    In my 13.5 years of school board service, I’ve cast my votes with a ‘student first’ philosophy.  Student interests, before adult politics.  The County Board in it’s recruiting for the the next County Superintendent of Schools says in its job flyer it seeks a County Superintendent that ‘is strongly committed to a “student first” philosophy in all decisions.’

    I’m confident this philosophy will be the ‘North Star’ as relates to the upcoming vote and beyond to guide our journey.

    Craig Mann
    Member, Santa Clara County Board of Education
    Reply
    Caroline Grannan Dec 13, 2011 @ 7:56 am

    As a public school advocate who has followed education “reform” and charter school for many years, I’ve watched the hyping of “miracle” after “miracle.” Anyone who’s familiar with the cycle of hype and flop should use common sense and proceed with prudence. Kids are at stake.

    The New York Times covered “miracle” cyber-charters today. The beneficiaries of the miracle are the opportunistic private investors into whose pockets these miracles are diverting our children’s education funding.

    http://www.nytimes.com/2011/12/13/education/online-schools-score-better-on-wall-street-than-in-classrooms.html?_r=1&ref=todayspaper
    Reply
    Beatrice Dec 13, 2011 @ 10:01 am

    We all know how this vote is going to go. No need for coy suspense.

    We also know that if you were really about kids, you’d take the elements of the Rocketship model that are scalable and replicable and spread them to all of the neighborhood schools in the county.

    Instead of building strong community schools in every neighborhood, your legacy will be their undoing.

    This isn’t creativity or leadership, it’s merely craven.
    Reply
    This is a win-win for the public schools -- and th Dec 14, 2011 @ 10:50 am

    I have—and continue—to support public schools, from my father’s 30 years teaching in them to more than five years of having a child in San Jose’s public schools. And I sincerely hope that SCCOE supports this effort, because in the long run it is clearly designed to benefit the children of the county—and the public schools.

    Look at the children the Rocketship schools have attracted; they are the children that San Jose Unified, for example, strives most to help—but does not serve well. A few reasons: lack of an extended school day, minimal expectations for high-achieving children, increasing lack of individualization, and abysmal leadership among school principals. (If anonymous evaluations of school leadership were offered by parents and by teachers, this would be documented in stark terms.) In addition, San Jose’s schools have in the past year taken steps to reduce the involvement of parents at elementary schools and clearly spent more time talking to lawyers (on how to retain funds for a voluntary integration program) than talking to parents about how to ensure children are receiving the best education possible.

    – Parent of a child in San Jose
    Reply
    Trish Williams Dec 13, 2011 @ 11:59 am

    Public education policy is a complicated arena, with so many legitimate and competing interests and issues at play. It is a complicated world.  I wish you all the best and appreciate your public service as you consider and vote on these critical issues.  But I agree with SCCOE member Mann in hoping that “students first” is the north star guiding the SCCOE’s deliberations.  Trish Williams, VP, CA State Board of Education
    Reply
        Craig Mann Dec 14, 2011 @ 1:09 am

        Trish – thanks SO much for your sober advice and well wishes.  I hope you and yours (SBE colleagues) will support the parents and teachers that supported petitions to have a Rocketship school in their community.  For instance, Rocketship East Palo Alto—that community really deserves the same great education that the folks on the other side of the freeway (Palo Alto) are being afforded. I taught in the Ravenswood SD for three years and can attest to just how underserved these students are.  I was born and raised in Oakland, another commmunity that needs better schools – not necessarily more.  Anyway, I respect what you do for students statewide and I really hope that the SBE realies just how invaluable Rocketship is to eliminating the achievement gap.

        Craig Mann
        Member, Santa Clara County Board of Education
        Reply
    Caroline Grannan Dec 14, 2011 @ 12:30 pm

    All I’m saying is don’t be naive and gullible, people. Use the common sense you were born with. We have heard hype about many supposed miracles from the so-called education “reformers” over the years. Many of their “miracles” have been total flops, none have been “miracles,” and many—including this one—are designed to funnel your children’s education funding into private pockets.

    Be skeptical, vigilant and questioning. Remember, many of the forces hyping this “miracle” were hyping Edison Schools as the “miracle” 10+ years ago. If it turns out to be a genuine miracle, you can be happily surprised then. This especially goes for the press.
    Reply
    Craig Mann Dec 15, 2011 @ 2:23 am

    I just got home from our County Board meeting and I am happy to report that a majority of the board mustered the courage act in a ‘student first’ philosophy and voted to approve each of the 20 Rocketship countywide-benefit charter schools tonight. Yes!… student interests prevailed ahead of adult politics smile It was a tough night and there were honorable persons that disagreed with me (the majority vote) and that is quite o.k. smile I was disappointed in some of the hyperbole, obsfucation, and canards posited by some, but it is a free country and folks are entitled to believe and say what they may. The good news, the GOOD NEWS is that students throughout our county will have 20 new schools to choose to attend beginning as early as 2013 (4 opening per year through 2017).

    Craig Mann
    Member, Santa Clara County Board of Education
    Reply
        Students First Dec 15, 2011 @ 5:02 am

        I appreciate your focus on students, Craig.  However, what is lost in this debate is the effect on students who don’t transfer to charters.  They are left behind in underfunded traditional public schools that are being abandoned by the families with greater school involvement and academic motiviation, to remain on a sinking ship.  The effect is that a greater fraction of the students are getting less service than before as families self-segregate between charters and the rest.
        Reply
            Bea Dec 16, 2011 @ 10:06 am

            StudentsFirst, I agree with all you’ve said here, save for the appreciation of trustee Mann. For someone who c,aims to be about kids, Mann is going to great lengths to do a lot of damage to the many more kids whose neighborhood schools will be undermined by this act through loss of human capital (the families you refer to), compounded financial loss, and the inevitable effects of academic apartheid that result from rapid, unfair competition between privately resourced agencies and financially starved public agencies.

            It won’t be long before all see the greater implications of a series of very bad decisions.
            Reply
    Unknown Educator. Dec 17, 2011 @ 8:01 am

    No Offense to Joe DiSalvo , he’s a great guy , he’s for reform . The Newly created Charter approval is now a ‘Genie’  out of the bottle . What’s next for approval at the County office of ED ? 
    Here is some ‘statistics’ about the county office of ed’s green light for the 20 NEW RocketShip Charters:

    That’s right, twenty, all from the same chain. In effect, that would make them the second-largest school “district” in Northern California’s most populous county, behind only San Jose Unified.

    But representatives of about a dozen local school districts argue that they, and not the county school board, should be the ones weighing the charter applications. “Districts are ready to work with charters and you are trying to stop that,” said Pam Parker, president of the Santa Clara County School Boards Association….

    The board voted 5-2 on most of Rocketship’s petitions, with trustees Anna Song and Michael Chang dissenting. Song chided Rocketship as untrustworthy, for claiming to be a school district in order to skirt local planning ordinances in building its schools, and for holding board meetings in places not easily accessible by the public. Chang said he preferred Rocketship to seek charters from local districts….

    Los Altos schools trustee Tamara Logan likened the county board’s approval of Rocketship charters to generals placing soldiers in people’s homes, appropriating their food and money without permission.

    This is basically the same old charter stuff with a glitzy Silicion Valley veneer. Lots of the usual suspects are represented on their borad or as partners: KIPP, Gates, TFA, New Schools Venture Fund, Broad.

    http://rsed.org/index.php?page=board-advisors

    http://rsed.org/index.php?page=partners

    Oh yes, the people who staff their “Learning Labs”, touted as key to their “hybrid school model”, make $14 an hour (in this high-wage market, that’s what an in-home caregiver makes) and aren’t required to have bachelor’s degrees.

    http://rsed.org/downloads/Individualized_Learning_Specialist_Job_Description Final.pdf

    And the kicker: they have a real estate arm, cutely called “Launchpad”—just like Imagine does.

    http://www.launchpad-dev.org
    Reply
        Teachable Moment Dec 19, 2011 @ 10:48 am

        > Los Altos schools trustee Tamara Logan likened the county board’s approval of Rocketship charters to generals placing soldiers in people’s homes, appropriating their food and money without permission.

        Tamara gets my vote for first place in the hyperbola competition.

        Otherwise, I have no idea what in hell she’s talking about.
        Reply

Leave a Reply

Your email address will not be published. Required fields are marked *

Comment

Name *

Email *

Website

Save my name, email, and website in this browser for the next time I comment.


Trending Articles

    Op-Ed: Something is Clearly Off with California’s Homelessness Spending3
    City of San Jose and Its Unions Are Deadlocked over New Contract3
    Unthinkable And Unconscionable2

Popular Topics

    Santa Clara County
    City Council
    Sam Liccardo
    San Jose
    COVID-19
    Silicon Valley

Advertise with San Jose Inside »
San Jose Inside | A look inside San Jose politics and culture

    News
    Opinion
    Investigative Reports
    The Fly
    Sports
    Real Estate
    People
    Calendar

Copyright © 2023 San Jose Inside. All rights reserved. | About Us | Comments Policy | Advertising & Partnerships | Contact Us | Facebook | Twitter

* Links to Rocketship-related court proceedings
- Post on withdrawal of 13 of the 20 charters in Santa Clara County:
  http://www.stoprocketship.com/rocketships-lawsuit-settlement-will-big-impacts-neighboring-districts/

- Settlement document on withdrawal of charters:
  http://www.stoprocketship.com/wp-content/uploads/2015/03/7A._Action_Item2.pdf
 
- Bymaster/SJUSD Lawsuit against Rocketship:
  http://www.stoprocketship.com/community-wins-major-lawsuit/

- https://www.mercurynews.com/2014/06/28/rocketship-education-changes-course-slows-expansion/

- https://www.mercurynews.com/2013/02/19/san-jose-unified-to-sue-county-school-board-over-rocketship-education/
 
- Text of initial ruling at Santa Clara County Superior Court
  http://www.stoprocketship.com/wp-content/uploads/2014/03/BYMASTER_VS_SCCOE_FINAL_RULING.pdf
 
- 6th District Appelate Court Ruling
  http://www.stoprocketship.com/wp-content/uploads/2019/03/Appellate-Decision.pdf
 
- State supreme court denies appeal, and ruling becomes final:
  http://www.stoprocketship.com/wp-content/uploads/2019/03/H041088-rmi.pdf
 
* Roxana Zoom url
https://sjsu.zoom.us/j/81143517371?pwd=Qi9UM1IrY29EbEJaZ3VIaVBoU1VVdz09 
Meeting ID: 811 4351 7371 
Password: 103895

* SB740 Conflicts of Interest regulations
- CCR Title 4, Division 15, Article 1.5 Charter School Facility Grant Program
- 10170.14. Conflicts of Interest.
- https://www.treasurer.ca.gov/csfa/csfgp/sb740/permanent-regulations.pdf
* [Obsolete] Things to do whenever ending an editing session on mozart.
1. [ ] Make sure everything builds.
2. [ ] Check modified files into Git.
3. [ ] Remove untracked files from the working tree.
4. [ ] If 'lsyncd' isn't running, rsync into local Dropbox.
5. [ ] Rsync into prokofiev/mozart from mozart/prokofiev.
6. [ ] Make sure both prokofiev and mozart build.
7. [ ] Check out of Work Log.log

* Four principles of high quality case studies
1. First, your analysis should show that you attended to all the evidence. Your analytic strategies, including the development of rival hypotheses, must exhaustively cover your key research questions (you can now appreciate better the importance of defining sharp as opposed to vague questions). Your analysis should show how it sought to use as much evidence as was available, and your interpretations should account for all this evidence and leave no loose ends. Without achieving this standard, your analysis may be vulnerable to alternative interpretations based on the evidence that you had (inadvertently) ignored.
2. Second, your analysis should investigate, if possible, all plausible rival interpretations. If someone else has an alternative interpretation for one or more of your findings, make this alternative into a rival. Is there evidence to address the rival? If so, what are the results? If not, should the rival be restated as a loose end to be investigated in future studies?
3. Third, your analysis should address the most significant aspect of your case study. Whether it is a single- or multiple-case study, you will have demonstrated your best analytic skills if the analysis focuses on the most important issue (whether defined at the outset of the case study or by working with your data from the “ground up”). By avoiding excessive detours to lesser issues, your analysis will be less vulnerable to the accusation that you diverted attention away from the main issue because of potentially contrary findings.
4. Fourth, you should demonstrate a familiarity with the prevailing thinking and discourse about the case study topic. If you know your subject matter as a result of your own previous research and publications, so much the better.
* Case study evidence can be
- documents,
- archival records,
- interviews,
- direct observations,
- participant-observation, and
- physical artifacts.
* Annual Financial Data (SACS forms and Alternative forms)
https://www.cde.ca.gov/ds/fd/fd/
* Grants to Rocketship for Replication and Expansion of High-Quality Charter Schools by Public Charter Schools Programs of U.S. Dept. of Education, 2009-2016

|    Year | Grantee              | Project Title        | Duration | Year 1     | Total Expected | City         | State |
| Awarded |                      |                      |  (Years) |            | Funding        |              |       |
|---------+----------------------+----------------------+----------+------------+----------------+--------------+-------|
|    2011 | Rocketship Education | Rocketship Education |        5 | $823,079   | $6,259,757     | Redwood City | CA    |
|    2017 | Rocketship Education | Rocketship Education |        5 | $5,090,134 | $12,582,678    | Redwood      | CA    |
|         |                      | CSP Replication      |          |            |                |              |       |

* Are there any CSFA restrictions on the amount of rent that  an entity can charge?
* What are the effects of RSEd on their district?
- financial
- academic
- political
- ethical
** SpEd costs
** District revenue or expenses
** District demographics
- Compare change in district vs surrounding districts before and after a Rocketship school opens
* Are any ratios (revenue:debt) of interest?
* Consider adding a "systematic literature search " process flowchart
- See p.64 of (OleksandraSkrypnyk.etal,2017)

* Don't forget to ...
** include property taxes not paid when calculating the value of an investment, especially the New Market Tax Credit.
** see if the initial or renewal petitions include bond principal and interest payments.
* Rephrase my research question to emphasize that
- The potential for making money is in real estate (by an order of magnitude)
- Other people have written about creaming, pushing out, teaching to the test, using non-unionized teachers, etc., but no one so far has written about making money through real estate.
* Questions for the  Assessor's Office
1. Plat Map 477-34-088: What's with the area immediately to the right labeled circle(15)? Is anyone paying taxes on that common area?
2. What does P.M. 845-M-39 mean?
3. Is there a Plat Map guide somewhere?
* Non-fiscal State Coordinators' Contact Information from 
California: California Department of Education
Thomas Bjorkman: tbjorkman@cde.ca.gov, 916-327-0193
* Common Core of Data (IES:NCES:CCD)
https://nces.ed.gov/ccd/aboutccd.asp
* Snippets
** Comparisons
\section{How Does Rocketship Compare?}\label{sec:comparisons}
\subsection{Demographic Data}
When searching for anomalous data, Rocketship schools, individually and collectively, need to be compared to traditional public schools and districts, but only after making any needed adjustments to account for the demographic contexts in which the schools operate. It makes no sense to compare the finances of, say, Rocketship Mateo Sheedy in San José with the finances of the Westside Union Elementary School in Los Baños, less than 65 miles away. One is a medium-sized charter school in a large urban school district, the other is a much larger public school in a rural public district. This means that demographic data must be used along with financial data to obtain valid and useful comparisons.

Raw demographic data is hard to use and impossible to visualize. In 1983, Edward Tufte self-published \citetitle{Tufte1983}, which revolutionized how we present data, especially quantitative data. Since then, not only have there been five other Tufte books, but there has been an explosion of high quality books on data visualization. Currently, the most useful guide to presenting data is \citeauthor{Schwabish2021}'s \citetitle{Schwabish2021}.  In it he offers more than 50 different kinds of charts and graphs, all with the goal of helping the reader make sense of the raw data. The chapters \textit{\titleref{ch:findings}} and \textit{\titleref{ch:discussion}} will make extensive use of these data visualization tools. The data demographic data itself will come from the following datasets that specialize in education:

\begin{itemize}
  \item Data from the United States Department of Education, primarily the National Center for Education Statistics (NCES). These datasets (~500) are searchable online using the Open Data Platform \url{http://nces.ed.gov/}. Of particular interest is the massive Digest of Education Statistics, produced annually from 1990 onwards. The Digest for 2019 runs to 651 pages.
  \item The NCES Open Data Platform can analyze over 15,000 data sets in its collection.
  \item The Institute of Education Sciences, which is part of the NCES, maintains DataLab, a tool to analyze a very large number datasets, some of which span years, thus enabling longitudional studies to be undertaken
  \item The Stanford Educational Data Archive (SEDA) is a carefully cleaned and curated dataset that includes

  \begin{quotation}\noindent\OnehalfSpacing%
    \ldots~a range of detailed data on educational conditions, contexts, and outcomes in schools and school districts across the United States. It includes data at a range of institutional and geographic levels of aggregation, including schools, districts, counties, commuting zones, metropolitan areas, and states. It includes measures of academic achievement, achievement gaps, school and neighborhood racial and socioeconomic composition, school and neighborhood racial and socioeconomic segregation patterns, and other features of the schooling system. \sourceatright{\parencite{Reardon.etal2021}}
  \end{quotation}
  
  \item The National Assessment of Educational Progress (NAEP), both the current results and the long-term trend results.
  \item The Early Childhood Longitudinal Studies (ECLS), kindergarten cohorts of 1998 \& 2011.
\end{itemize}

** Comparisons
A comparison of Rocketship schools with public schools will require more than just financial statements. For example, answering a question like, ``Do Rocketship schools have higher administrative costs compared to nearby public schools?'' requires not only financial data, but also knowledge of student demographics to ensure that a like comparison is being made. For example, one district may send its special needs children to an adjacent district that is known to serve special needs children particularly well. The sending district will spend less on administrators and the receiving district more, skewing a straight up comparison.
** Themes
Several themes run through this study. The first is Rocketship's relationship to the privatization movement in education. The second is how Rocketship's finances drive its need to expand. The third is how Rocketship needs continued marketing and public relations to survive.
** Rent & sale price
because the sale price of commercial property is mostly the present value of an income stream (the gross rent) whereas the cost is the present value of the stream of net rent. I.e. the charter needs to borrow (or forgo investing) the net rent, and the interest paid or foregone represent the cost of borrowing the net rent. Since the net rent is much lower than the market rate, the owner makes a tidy profit. In addition, the risk associated with the purchase is significantly lower than usual.
** Dreambox
For example, Rocketship bought from Dreambox the software it uses in blended learning. Creating software for blended learning is not hard. In fact, there are a half-dozen or more free, open-source learning platforms that can be re-skinned (i.e. given a new look-and-feel). Some of these platforms have been around for decades and are therefore quite robust. They are also extensible, either with plugins or via an API, and at worst, the source code itself can be modified. So, the per-pupil cost of blended learning software should be low compared to bespoke software. If this is not the case, then Rocketship would be overpaying and the amount of overpayment is profit which accrues to the software vendor, not Rocketship.

** Discussion
#+BEGIN_SRC latex
\subsection{Construct Validity}
\textit{Construct validity} is the extent to which a case study's choice of what to measure actually measure what it claims to measure. Our intent is to measure how much profit Rocketship produces. If we choose to use the financial statements of Rocketship Education and associated entities, will they provide a comprehensive enough of a picture of Rocketship's finances to measure how much profit Rocketship generates? Here we are actually asking two questions:

\begin{enumerate}
  \item Are the financial statements which exist trustworthy?
  \item Do financial statements provide a complete view into Rocketship's finances?
\end{enumerate}

An answer to the first question can be provided by remembering Enron and noting that it fooled all of the people for quite some time. For charter schools, we note that there is a constant stream of charter school fraud that's being uncovered, despite requirements for annual audits. Even worse, in some cases, there is a complete absence of financial statements because many charter school chains are operated by and perhaps owned by a private entity. As private entities, these charter school operators are entitled to keep their finances secret. So, unfortunately, the answer to the first question must be, no, the financial statements which do exist, if they exist, are not necessarily trustworthy. We can use triangulation to fill in gaps and to cross-reference. It is very hard to cover all of one's tracks.

One is tempted to infer that whenever a private, for-profit charter school chain refuses to open its books to public inspection, there is likely something of material significance it wishes to hide. This, however many times it proves to be correct, is still an unwarranted generalization.

The answer to the second question above is: perhaps. If one assumes that there are annual, certified audits, then at least part of a charter school's finances are visible and add up. But, what's not accounted for are transactions that are not arm's length, i.e.~they are self-dealing. Yes, the books are available for inspection, and they balance, but the probity of the transactions is questionable at best and fraudulent at worst.

In the end, we are left with some doubt and suspicion, even if everything adds up. We do find unexplained anomalies, books which don't balance, or money which has simply disappeared and no explanation is forthcoming, we can be confident that we have uncovered something illegal.

\subsection{Internal Validity}
\textit{Internal validity} concerns the completeness and appropriateness of any proposed cause for a set of phenomena. \citeauthor{Yin2018} says,
\begin{quotation}\noindent\OnehalfSpacing%
  [T]he concern over internal validity, for case study research, extends to the broader problem of making inferences. Basically, a case study involves an inference every time an event cannot be directly observed. An investigator will “infer” that a particular event resulted from some earlier occurrence, based on interview and documentary evidence collected as part of the case study. Is the inference correct? Have all the rival explanations and possibilities been considered? Is the evidence convergent? Does the evidence appear to be airtight? \parencite{Yin2018}
\end{quotation}

This dissertation depends the internal validity of documentary evidence, namely, Rocketship's financial statements. These are declared to be true and accurate, to the best of the preparer's knowledge, under penalty of perjury, a strong but not absolute guarantee of their truthfulness and accuracy.

\subsection{External Validity}
\textit{External validity} is the extent to which a study's finding can be applied to other events or situations. Can the explanations given be applied to other charter school chains? If the purpose of this study is to change public policy to better serve kids, then the phenomena examined, described, and explored should be useful in more than just Rocketship's case.

\subsection{Reliability}
A case study is said to be \textit{reliable} when similar findings obtain from similar data. Would another researcher come to the same conclusions when presented with Rocketship's financial data? If the answer is yes, then the case study may be said to be reliable.

\subsection{Rival Explanations}
\textit{Rival explanations} are alternative ways of looking at the data and drawing alternative conclusions. The following sections look at Rocketship from the point of view of political economy, <stuff>.

\subsubsection{\textit{The Political Economy of Public Policy}}
\citefirstlastauthor{BuenoDeMesquita2016} in \citetitle{BuenoDeMesquita2016} proposes that we should evaluate public policy issues using \textit{models} which are then themselves evaluated using different \textit{normative} lenses. \textcite[13–47]{BuenoDeMesquita2016} offers three normative frameworks for us to consider:
\begin{itemize}[nosep]\OnehalfSpacing%
  \item \textbf{Utilitarianism} A public policy is right or wrong, good or bad, valuable or not based on the policy's consequences. Right and wrong, good and bad, valuable and not valuable are collapsed into the notion of \textit{utility}. Policies with greater aggregate utility should be pursued; those with less utility should not.
  \item \textbf{Egalitarianism} Public policy should be evaluated using the notion of \textit{equality}. One might consider equality of \textit{outcomes} or of \textit{opportunity}.
  \item \textbf{Kantian Deontology} The worth of a policy is to be judged by its conformance to some moral norm or duty. These norms are frequently expressed as \textit{rights}, which, in turn, imply a \textit{duty} to others to honor those rights.
\end{itemize}

These three normative lenses allow us to evaluate Rocketship's worth. Does it increase society's utility? And, does it do so without making others worse off (a \textit{Pareto improvement}). Does it create equality of outcomes or of opportunity? Finally, does it honor some rights that people claim they have?

\section{Limitations}
It is always fair to ask what the limitations of a study or research are, and how valid are its conclusions. High quality studies make an effort to address legitimate objections that might be raised. In addition, social science studies often have policy implications: ``How should public policy change to advance the common good in light of the study's finding?''

Unfortunately, in general, there are more ways that a study could be limited than there are ways of producing a robust study. A single omission or error can doom a study, but to be valuable and to be able to withstand objections, a study has to get everything right. These issues are not as acute for case studies, like this dissertation, because no data amenable to statistical analysis is being collected or analyzed. Instead, the question is, ``Has the study captured everything of relevance?'' In this dissertation, since I'm examing Rocketship's finances, I need to asssure myself that I have gathered \emph{enough} relevant financial data to draw sound conclusions. In principle, independent auditor's annual reports would be sufficient because the purpose of an independent annual [financial] audit is to present all of the material and financial information needed by regulators, investors, employees, and other stakeholders. Fortunately, there are supplemental data that have the same coverage: the annual budget, and the first and second interim reports. All four should match pretty closely when they are compared.

Since Rocketship schools are charter schools, there additional sources of financial data are available. Charter schools, to be approved, must submit a petition, one of whose required elements is a description of ``financial statements that include a proposed first-year operational budget, including startup costs, and cashflow and financial projections for the first three years of operation.'' (CA Ed. Code §47605(h)). Similarly, charter school renewals have a financial component. Finally, if a charter school is a nonprofit public benefit corportation as Rocketship Education is, there are additional federal financial reporting requirements (IRS Form 990). Again, the data in these documents should tell roughly the same story.

To sum up the limitations of this dissertation, the financial reporting net around Rocketship is comprehensive. However, there is a big loophole: charter schools in California are allowed to contract out all of their operations to a for profit corporation which may keep its finances secret. Effectively, these charter schools can evade most but not all of the financial reporting requirements that apply to nonprofit public benefit charter schools. Rocketship is, however, a nonprofit corporation, so it must expose all of its finances, and anything which is not reported may be obtained using a CPRA (California Public Records Act) request.

One may argue that charter schools were born out of racism and continue to perpetuate that racism. They are merely the educational version of privatization, a movement driven by a search for profit, not educational excellence. They appear to be the social project plaything of billionaires.

\section{Future Research}
One of the realizations that comes from researching charter schools is exactly how massive the marketing of charter schools is. Not only are there think tanks that churn out reports extolling every possible benefit of charter schools, but there are many advocacy organizations whose only purpose is to advocate, advocate, advocate. And behind these think tanks, advocacy organizations, and charter schools, funding them, are a network of right-wing, secretive donors, captains of industry.

Some questions which could be asked are:
\begin{itemize}[nosep]\OnehalfSpacing%
  \item Is there a relationship between LCFF supplemental and concentration grants and Rocketship locations?
  \item How many charter school facilities bonds have defaulted?
  \item What factors make a location desirable to a charter school?
  \item What is the IRR (internal rate of return) of charter school venture funds?
  \item Is there competition among charter schools within a district? If competition among charter schools isn't present, is there a tacit agreement not to poach students?
\end{itemize}
\end{comment}
#+END_SRC

* Whom did it benefit? (Cui Bono Fuerit)
– Longinus Cassius

* Lucius Cassius ille quem populus Romanus verissimum et sapientissimum iudicem putabat identidem in causis quaerere solebat 'cui bono' fuisset.
The famous Lucius Cassius, whom the Roman people used to regard as a very honest and wise judge, was in the habit of asking, time and again, 'To whose benefit? - Marcus Tullius Cicero


* Copyrights
- See [[https://copyright.lib.harvard.edu][Copyright at Harvard Library, State Copyright Resource Center]]
- ee [[https://en.wikipedia.org/wiki/Copyright_status_of_works_by_subnational_governments_of_the_United_States#California][Copyright status of works by subnational governments of the United States:California]]
- In 2009, the California Court of Appeal for the Sixth District, which has statewide jurisdiction, ruled, in County of Santa Clara v. California First Amendment Coalition, that the California Public Records Act did not provide authority for copyrighting government records subject to disclosure under the act. The Court noted that other provisions of California law do expressly provide for the copyright of specific types of materials created by the state.[5] The court noted that:

The Legislature knows how to explicitly authorize public bodies to secure copyrights when it means to do so. For example, the Education Code includes a number of provisions authorizing copyrights, including this one: "Any county board of education may secure copyrights, in the name of the board, to all copyrightable works developed by the board, and royalties or revenue from such copyrights are to be for the benefit of the board securing such copyrights." (Ed. Code, § 1044; see also, e.g., id., §§ 32360, 35170, 72207, 81459.) 

* Big ToDos for 0.

\begin{comment}
This section provides a general introduction to the area of study and presents the problem to be
investigated in the study. The purpose of the study needs to be clearly stated and describe the
following:
a. The unresolved issue in education
b. The significance of the problem
c. The justification for investigating the problem
d. An explanation of the importance of conducting a study to help resolve that issue
e. Initial definitions for important terms and concepts likely to be used throughout the proposal
\end{comment}

* <2022-03-04 Fri> with Roxana
- Meet next Friday @ 10am
- Clean draft due by early Wednesday AM

* A /perfect/ market is one where
- Everyone is a price-taker
- Transaction costs are zero
- There are no barriers or costs to entry or exit
- Everyone has the same information, at the same time, that might affect prices
and the (surprising) consequence is that profits are zero for everyone.

* Charter School Plans
- "The Great Public Schools Now Initiative, Broad Foundation, June 2015
- "The Wave of the Future", Andrew Smarick, /Education Next/, v8 #1, Winter 2008
- "American Revolution 2.0: How Education Innovation is Going to Revitalize America and Transform the U.S. Economy", Michael Moe, et al, GSV Asset Management, July 2012
- "GSV 2020: A History of the Future", Michael Moe, et al, Global Silicon Valley, Fall 2015
* Caliber, Success Academy & Navigator are modeled on Rocketship
- RS is an early chain & is rapidly expanding
- Complex intersection of charter school and construction/facilities company
* How to create an importable-into-LaTeX graphic from a PDF
- In Windows, use Adobe Acrobat Pro DC to edit the PDF.
- Select the image and copy it.
- Create a blank PDF and insert the image
- Crop it and trim the page to the image.
- Save as a EPS file
- Import into Linux
- Use 'pdftocairo' to convert it to EPS:

  $ pdftocairo -eps file.pdf file.eps

- Use includegraphics to get it into the LaTeX PDF output
* Semi-automatic index generation
indexmeister & imbrowse
* [[https://www.cbinsights.com/company/rocketship-education/financials][Investors in $14M Rocketship Education Funding, Valuation, and Revenue]]
- Kleiner Perkins Caufield & Byers
- Menlo Ventures
- Accel
- Benchmark
- Technology Crossover Ventures
- NewSchools Venture Fund
- Reed Hastings
- Charter School Growth Fund
- Sheryl Sandberg
- Jonathan Chadwick
- Arthur and Toni Rembe Rock
- Peery Foundation
- Charles and Helen Schwab Foundation
- Tipping Point
* For Roxana on <2021-09-07 Tue>:
- I've taken the summer off.
- I'm fully committed to finishing my dissertation by April 1st. That gives me 6 1/2 months. I think I can commit to 6 hours per weekday.
- I think I'm halfway done for a draft of Chapter 3 good enough to use as a proposal. End of September (or earlier).
- I still need help on crafting good research questions. What's my point?
- What happened to the /Cashing in on Kids/ web site? Too much work for too few views?
- I'm getting pretty discouraged by the steady stream of political setbacks:
  - Texas: anti-abortion & voting rights
  - Biden's ratings
    - Are we supporting him as much as we should?
  - Senators Manchin & Sinema
  - the continued focus on a stolen election
  - the continued absence of focus on the Jan 6th attempted coup
  - the continued absence of focus on Facebook's role in spreading disinformation
  - Jane Mayer's article in the /New Yorker/ on the funding of voter suppression
  - Article on the success of anti-vaxxers in the NY Times 31-Aug-2021, "This is the Moment the Anti-Vaccine Movement Has Been Waiting For"
  - What the hell is wrong with progressives? Why can't we win more often?
  - Newsom & the recall & Reed Hastings & <one other billionaire whose name I forget>
* From 2021-01-12 issue of the Cashing in on Kids newsletter:
Which federal agency has funded more charter school facilities than any other? The U.S. Department of Agriculture. At least according to Chicago-based Wert-Berate,r LLC, the self-described “leading” company in facilitating the charter school industry’s lucrative real estate sector by providing “feasibility studies.”

+-----------------------+----------------------+-------------------------+-------------------------+
|                       | *Private*              | *Charter*                 | *Public*                  |
|-----------------------+----------------------+-------------------------+-------------------------|
| *Funding*               | private              | tax dollars             | tax dollars             |
| *Governance*            | self-appointed board | self-appointed board    | elected board           |
| *Duration*              | unlimited            | time-limited+renewal    | unlimited               |
| *Ed. Code*              | no                   | no                      | yes                     |
| *Taxation Powers*       | none                 | none                    | limited                 |
| *Facilities Bonds*      | yes                  | yes                     | yes                     |
| *Admissions*            | limited              | limited # (lottery)     | unlimited               |
| *Unionized*             | rarely               | perhaps                 | usually                 |
| *Curriculum*            | completely flexible  | flexible                | mostly fixed            |
| *Standardized Testing*  | no                   | yes                     | yes                     |
| *Accountable*           | no                   | yes, to state & charter | yes, to state & parents |
| *Teacher Certification* | sometimes            | usually                 | often not               |
| *Teacher Pension*       | perhaps              | perhaps                 | yes                     |
|                       |                      |                         |                         |
+-----------------------+----------------------+-------------------------+-------------------------+
* The structure of a case study, doctoral dissertation
From /The Dissertation Journey: A Practical and Comprehensive Guide to Planning, Writing, and Defending Your Dissertation, 3/e/, by Carol Roberts and and Laura Hyatt.
- Chapter 1 Problem and purpose
- Chapter 2 Literature review
- Chapter 3 Methodology
- Chapter 4 Case studies
- Chapter 5 Analysis of themes
- Chapter 6 Conclusions, implications, and recommendations
* The charter school industry /modus operandi/
1. Paint a bleak picture of public failure school failure
   - PISA scores suck & have sucked for a long time.
   - Performance is critical to the long term economic success and military security of the United States.
   - More money doesn't help; schools already have gobs of money.
2. Surreptitiously slide into bashing and demonizing {teachers, unions, politicians, socialists, academics, and bureaucrats}, i.e. those who have the knowledge and training to counter the claims and arguments of the charter school industry.
3. Advance a "solution" that ... wait for it ... creates profits. What a surprise.
4. Along the way, call what you're doing with a name which means the opposite of what you're actually doing.
   - Call charter schools "public schools" but don't let the public have any voice in their operation.
   - Claim to put children first, but actually put profits first. 
   - Use words like "academy", "heritage", and "success" to create an aura of long-time academic success.
   - Claim to "innovate", but actually impose a completely profit-oriented structure. 
   - Call yourself "grassroots" but fund your organization with the donations of billionaires.
   - Aggressively promote yourself despite having no educational experience.
** Public schools need to be failures in order for charter schools to be the solution.
- So, starve public schools of funds, ensuring that they can never meet their goals.
- Impose impossible mandates, like
  - No Child Left Behind (no child, zero, not even one child, an impossible goal)
  - Require (but do not fund) that all children, including those with special needs, be educated. Test them, just to make sure.
  - Design standardized tests administered to *all* students that
    - are age-inappropriate
    - have cut scores that fail 50% (or more) who take them
    - report their results after they might conceivably be useful to teachers
    - are adaptive so that no two students take the same test
    - are secret, so that no public estimate of their reliability, validity, or appropriateness can be calculated
  - Ask schools to address & correct failures over which they have no or little control, like closing the achievement gap or eliminating segregation and discrimination. This, the key mandate of NCLB, is impossible for schools to meet.
- Hold schools accountable for meeting these impossible mandates, and closing those which fail.
- Ignore all issues involving race, diversity, or culture.
* Charter schools must comply with the California Building Standards Code (Part 2 (commencing with Section 101) of Title 24 of the California Code of Regulations)
Do public school districts have to comply? What happens if the district facilities used by the charter schools don't comply?
* Be careful to not appear prejudiced; be neutral.
* Give a context:
- 7000 charter schools
- save bymaster story for acknowledgements
  Support Our Schools Community Discussion Sunday, September 22, 2019 at the Southside Community Center in San José
  *Starts 2:30 pm*
  <https://voteclaudiarossi.us17.list-manage.com/track/click?u=0b057fa2b299f9229ea562485&id=2c7113f90f&e=9cf7b4608e>
  Students are back in the classroom and we want to have a discussion about
  supporting public education. Join parents, neighbors and educators for an
  in-depth conversation and meeting about ways we can support our public
  education system, our teachers and our youth. See flyer for full
  information. 

  We are honored to be joined by Rev. Moore & Roxana Marachi from the NAACP,
  Trustees Brian LoBue & Brian Wheatley and education champion Pastor
  Bymaster.

  This is event is provided with support by the San José/Silicon Valley
  NAACP, In The Public Interest, South Bay Progressive Alliance and BACKPACS
  (Bay Area Collective Keeping Privatizers Away from Community Schools.)

  Our schools and our children need our help, and begins with ensuring the
  community's voice is heard. Please share this event with friends and
  neighbors. I look forward to our September 22 event. Thank you.

-  In solidarity.

  Sincerely,
  <Claudia Rossi>

* Why is my study interesting
- heated debates
- many chains
- will focus on Rocketship
- corporate vs community
- avoid one sentence paragraphs
- assumption
- research have found that this effect...
- deep dive to document
- must be replicable and defendable
- charter schools expansion is complicate
- so and so have found....
- quantify the effect -> document the effects that RS
- "data are"
  
<2021-04-27 Tue>
* Charter Fund
– dba Charter School Growth Fund
- EIN: 84-1049083
* <2021-04-29 Thu> with Arnie
** Purpose: Evaluate Rocketship
** Purpose: A case study
** Robert Stake, Robert Yin
*** to what extent do RS policies serve all students? 
** Send Arnie my research questions and what i want to do, and he'll suggest derived RQs.
*** add IRB + "citi" to Chapt. 3 submission
* <2021-04-29 Thu> With Roxana
** KIPP not Rocketship is the largest CMO. "Is among" "is one of the largest"
** Charles Schwab?
** Caliber, avigator, KIPP
** Move Jefferson & Gandhi to Introduction
** "so little to lose" -> don't have a voice
** RQ use "unduplicated students"
** Latino ELL students do worse than ELL students in public schools even though RS claims to be closing the achievement gap
** if you will
** concision is important
** check on CA's non-classroom based instruction moratorium expiring soon
* <2021-05-19 Wed> With Roxana
** Work hard, be hard
Little work on
answer with data that can be replicated
** systematic study
-  RQ: different factors influence relate to RS's
how do  cmo structure, bl pedagogy, location 
  affect RS's finances
  what is the role?

  examine various factors aspects profits from tax dollars

- what are the ways that non-profit charter school chains derive profits from public funds
- Does RS only invest in locations where LCFF funding gives unduplicated pupils extra $$$
- sacklers invest in charter schools
  - highlight benefits
  - downplay difficulties
  - Sackler – Rocketship???
    "a walking conflict of interest" – description of Sackler
