(TeX-add-style-hook
 "Methods"
 (lambda ()
   (setq TeX-command-extra-options
         "-recorder")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "ch:methods"
    "sec:process-overview"
    "sec:financing-ca-overview"
    "fig:2019–20_K–12_Funding"
    "sec:budgets"
    "sec:lcaps"
    "sec:CAFRs"
    "sec:charter-school-financing"
    "sec:charter-financial-docs"
    "tab:charter-fin-docs"
    "sec:cs-petitions-renewals"
    "sec:cs-staff-reports"
    "sec:budgets-etc"
    "sec:cs-lcaps"
    "sec:board-committee-packets"
    "sec:real-estate"
    "sec:facilities-options"
    "tab:charter-facilities-options"
    "sec:co-locating"
    "sec:leasing"
    "sec:owning"
    "sec:funding-facilities"
    "tab:paying-for-facilities"
    "sec:private-funding"
    "sec:venture-funds"
    "sec:tax-credits"
    "sec:bond-prospectuses"
    "other-data"
    "sec:state-federal-filings"
    "sec:curated-social-media"
    "sec:gaps-anomalies"
    "sec:triangulation")
   (LaTeX-add-index-entries
    "dissertation!design of|("
    "dissertation!design of|)"
    "dissertation!finance|("
    "dissertation!finance|)"
    "school funding!example of|("
    "school funding!example of|)"
    "dissertation!process used by|("
    "dissertation!process used by|)"
    "budgets|("
    "budgets|)"
    "budget cycle|("
    "budget cycle|)"
    "LCFF|("
    "LCFF|)"
    "Proposition 98|("
    "Proposition 98|)"
    "basic aid"
    "comunity funded"
    "K-12 funding!comprehensive description of (fn)"
    "budgets!annual"
    "budgets!interim reports"
    "budgets, audited"
    "LCAP|("
    "Local Control Accountability Plan (LCAP)"
    "LCAP|)"
    "Comprehensive Annual Financial Reports (CAFRs)|("
    "Comprehensive Annual Financial Reports (CAFRs)|)"
    "financial liability!auditors"
    "charter schools!financing of|("
    "charter schools!financing of|)"
    "charter schools!initial petition"
    "charter schools!renewal petition"
    "charter schools!budget"
    "charter schools!LCAP"
    "charter schools!interim reports"
    "charter schools!CAFR"
    "charter schools!initial petition|("
    "charter schools!initial petition|)"
    "charter schools!initial petition!required elements|("
    "charter schools!initial petition!required elements|)"
    "charter schools!petitions!publicly available|("
    "California Public Records Act (CPRA)"
    "Freedom of Information Act (FOIA)"
    "charter schools!petitions!publicly available|)"
    "Rocketship!annual financial statement|("
    "Rocketship!501(c)(3) non profit|("
    "Rocketship!501(c)(3) non profit|)"
    "Rocketship!annual financial statement|)"
    "charter schools!petitions!staff reports|("
    "charter schools!petitions!staff reports|)"
    "charter schools!annual filing requirement|("
    "charter schools!annual filing requirement|)"
    "charter schools!interim reports|("
    "charter schools!interim reports|)"
    "charter schools!CAFR|("
    "charter schools!CAFR|)"
    "charter schools!LCAP|("
    "charter schools!LCAP|)"
    "Rocketship!board meetings|("
    "Rocketship!board meetings|)"
    "charter schools!facilities!options for|("
    "charter schools!facilities!options for|)"
    "charter schools!real estate documents|("
    "charter schools!real estate documents|)"
    "charter schools!facilities!co-location|("
    "charter schools!facilities!co-location|)"
    "charter schools!facilities!leasing|("
    "charter schools!facilities!leasing|)"
    "charter schools!facilities!owning|("
    "charter schools!facilities!financing of|("
    "charter schools!facilities!financing of|)"
    "California!FPPC Form 700, Statement of Economic Interests|("
    "California!FPPC Form 700, Statement of Economic Interests|)"
    "Internal Revenue Service Form 990|("
    "Internal Revenue Service Form 990|)"
    "social media|("
    "social media|)"
    "gaps and anomalies|("
    "gaps and anomalies|)"
    "triangulation|("))
 :latex)

